AppBundle\Entity\Product:
  type: entity
  table: product
  id: 
    id: 
      type: integer
      generator: 
        strategy: AUTO
  fields:
    name:
      type: string
      lenght: 255
      nullable: false
      column: name
    category:
      type: string
      lenght: 255
      nullable: true
      column: category
    sku: 
      type: string
      lenght: 80
      nullable: true
      column: sku
    price:
      type: integer
      nullable: false
      column: price
    quantity:
      type: string
      lenght: 50
      nullable: true
      column: quantity